insert into article ( title, content) values ('Ms', 'Tunnel, The');
insert into article ( title, content) values ('Honorable', 'Loveless, The (Breakdown)');
insert into article ( title, content) values ('Honorable', 'Silent Action');
insert into article ( title, content) values ('Honorable', 'Carriers');
insert into article ( title, content) values ('Ms', 'Shaolin Temple 3: Martial Arts of Shaolin (Nan bei Shao Lin) (Martial Arts of Shaolin)');
insert into article ( title, content) values ('Ms', 'Man''s Best Friend');
insert into article ( title, content) values ('Dr', 'Hawk the Slayer');
insert into article ( title, content) values ('Ms', 'Personal Journey with Martin Scorsese Through American Movies, A');
insert into article ( title, content) values ('Mr', 'Empire Records');
insert into article ( title, content) values ('Honorable', 'I''m So Excited (Los amantes pasajeros)');
